[tasks.frontend]
description = "Avvia il frontend con Trunk"
command = "trunk"
args = ["serve"]
cwd = "frontend"

[tasks.start]
description = "Avvia il frontend"
script = [
    "cargo make frontend"
]